const cekHariKerja = (day) => {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        const dataDay = ["senin", "selasa", "rabu", "kamis", "jumat"];
        let cek = dataDay.find((item) => {
          return item === day.lowerCase;
        });
        if (cek) {
          resolve(cek);
        } else {
          reject(new Error("Hari ini bukan hari kerja"));
        }
      }, 3000);
    });
  };
  
    cekHariKerja("senin")
    .then((response) => console.log(response))
    .catch((response) => console.log(response));
  
  async function cek(day) {
    try {
      const hari = await cekHariKerja(day);
      console.log(`${hari} hari kerja`);
    } catch (error) {
      console.log(error);
    }
  }
  cek("selasa");

//perbedaan utama terletak pada structure dan fungsi dari then dan try
//then-catch digunakan pada promise sedangkan try catch digunakan pada asyn await
//then methode dapat digunakan sebagai pengganti callback ketika value pada promise bernilai resolve, 
//sedangkan catch digunakan sebagai error.
//pada try catch terdapat pengkondisian dan error handling
